### ISSUE TITLE
Re-optimization

### ISSUE THREAD

**Issue by ronkpunk** [tinify/wordpress-plugin#14]
Hi, It happen sometimes that plugin process stop with server errors (timeout or anyother).
In theese cases the plugin consider as optimized the image where error happen. 
Is it possible to force optimization after first run?

I think it'll be usefull if a user choose to resize original images to re-process all images

Thank you in advance
Stefano

**Comment by tinify-support** [comment]
Hi Stefano,

Thanks for contacting us. These errors usually happen if the
servers are under high load. We are currently working on
improving our infrastructure which should help with these types
of errors. The plugin will never consider an image "optimized" if
it hasn't actually been optimized - no matter the error. It can
happen that you receive an error but the image has been actually
optimized. If some images fail to optimize after doing a bulk
optimization, you can always run it again and it will try to
recompress only the image that have not been optimized the first
run.

For the bulk optimization functionality simply visit the bulk
optimization page under Media >> Bulk optimization.

Hope that answers your questions!

If not do not hesitate to let us know and we'll assist you
further.

Kind regards,

Evert Rotshuizen

tinify/wordpress-plugin on June 8, 2017 at 5:15pm wrote:

Hi, It happen sometimes that plugin process stop with server
errors (timeout or anyother).

In theese cases the plugin consider as optimized the image where
error happen.

Is it possible to force optimization after first run?

I think it'll be usefull if a user choose to resize original
images to re-process all images

Thank you in advance

Stefano

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/tinify/wordpress-plugin/issues/14 ), or mute
the thread
